name: '[CI] check build'

on:
  workflow_dispatch:
  pull_request:
    branches:
      - develop

permissions:
  contents: read

jobs:
  check-build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Lint app
        run: pnpm lint

      - name: Check for TypeScript errors
        run: pnpm typecheck
